# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kacoulib <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/14 11:15:32 by kacoulib          #+#    #+#              #
#    Updated: 2016/11/14 12:24:56 by kacoulib         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FLAGS	= -Wall -Werror -Wextra

all :
		gcc $(FLAGS) ./ft_display_file.c -o ./$(NAME)
clean :
		rm -rf *.o

fclean : clean
		rm -rf $(NAME)
